### ISSUE TITLE
Error. Variable missing

### ISSUE THREAD

**Issue by felixsanz** [JesseLeite/an-old-hope-syntax-atom#18]
Variable `@syntax-result-marker-color;` is used in base.less but it's missing its value.

```css
atom-text-editor .search-results .marker .region,
:host .search-results .marker .region {
  background-color: transparent;
  border: 1px solid @syntax-result-marker-color;
}
```
